// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijHBuFSLDsvjLiiuTVlABB7s-w5g1MUk',
    appId: '1:230724035847:web:2ef82cfcd075e23a1c91a2',
    messagingSenderId: '230724035847',
    projectId: 'what-with-my-car',
    authDomain: 'what-with-my-car.firebaseapp.com',
    storageBucket: 'what-with-my-car.appspot.com',
    measurementId: 'G-44HWDTKKE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmMFiMwZA_k9I96HtV4gY_uFcghLFzJkk',
    appId: '1:230724035847:android:9764f7dde987fcdc1c91a2',
    messagingSenderId: '230724035847',
    projectId: 'what-with-my-car',
    storageBucket: 'what-with-my-car.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIM6D-xoAUoIe3nPG34LFO-rg10tHg89M',
    appId: '1:230724035847:ios:6cd10ec08969db2a1c91a2',
    messagingSenderId: '230724035847',
    projectId: 'what-with-my-car',
    storageBucket: 'what-with-my-car.appspot.com',
    iosBundleId: 'com.example.whatWithMyCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIM6D-xoAUoIe3nPG34LFO-rg10tHg89M',
    appId: '1:230724035847:ios:ee2a1fde066bea1b1c91a2',
    messagingSenderId: '230724035847',
    projectId: 'what-with-my-car',
    storageBucket: 'what-with-my-car.appspot.com',
    iosBundleId: 'com.example.whatWithMyCar.RunnerTests',
  );
}
